basic:
    name: 'Alliance Direct Benefits (JOIN & MEMBERS)'
    breakpoints:
        - 640
        - 960
        - 1200
    pages:
        - 'https://join.alliancedirectbenefits.com/Checkout/MemberInfo'
        - 'https://members.alliancedirectbenefits.com'
    monitoring:
        days: [Sun]
        type: weekly
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
